mode=fill

wallpaper_folder=/home/2kfi/Pictures
preload= /home/2kfi/Downloads/neon-shacks-nord.png
preload= /home/2kfi/Downloads/nord.png
shuffle=true

wallpaper=HDMI-A-1,/home/2kfi/Downloads/neon-shacks-nord.png
wallpaper=LVDS-1,/home/2kfi/Downloads/nord.png
